CREATE TABLE `scans` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text,
	`patient_name` text NOT NULL,
	`scan_image_url` text NOT NULL,
	`previous_scan_image_url` text,
	`previous_scan_id` integer,
	`prediction` text NOT NULL,
	`confidence` integer NOT NULL,
	`status` text NOT NULL,
	`details` text NOT NULL,
	`scores_json` text NOT NULL,
	`comparison_note` text,
	`border_color` text NOT NULL,
	`badge_class` text NOT NULL,
	`text_color` text NOT NULL,
	`bg_color` text NOT NULL,
	`border_highlight` text NOT NULL,
	`ai_model` text NOT NULL,
	`processing_time` real NOT NULL,
	`image_quality` text NOT NULL,
	`dataset` text NOT NULL,
	`scan_date` text NOT NULL,
	`created_at` text NOT NULL
);
